version: '2'
services:
  web:
    image: odoo:13
    depends_on:
      - postgres
    ports:
      - "2513:8069"
    volumes:
      - odoo-data-volume:/var/lib/odoo
      # untuk file config berada di container
      - /home/ariev/odoo13-docker/config/odoo13.conf:/etc/odoo/odoo.conf
      # jika file config berada dihost gunakan ini
      # - /etc/odoo/odoo.conf:/etc/odoo/odoo.conf 
      
      - ./addons:/mnt/extra-addons
    environment:
      - PASSWORD_FILE=/run/secrets/postgresql_password
    secrets:
      - postgresql_password

  postgres:
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgresql_password
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db-data-volume:/var/lib/postgresql/data/pgdata
    secrets:
      - postgresql_password

volumes:
  odoo-data-volume:
  db-data-volume:

secrets:
  postgresql_password:
    file: ./config/odoo_pg_pass